# Generated by Django 2.2.6 on 2020-01-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='info',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.Edition'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
